blank_issues_enabled: true
contact_links:
  - name: 讨论区 / Discussions
    url: https://github.com/Mr-sans-and-InitLoader-s-team/Escape-From-Duckov-Coop-Mod-Preview/discussions
    about: 如需讨论或提问，请使用Discussions / Use Discussions for general questions and discussions
